---
title: "ML Final"
author: "Andrew Lewis"
date: "2024-11-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
training <- read_csv("https://raw.githubusercontent.com/IAA-Faculty/statistical_foundations/master/tele_churn3.csv")
```

```{r}
library(tidyverse)
nrow(training %>% filter(churn == 1))
```

```{r}
library(earth)
mars <- earth(churn ~ `total day charge`, data = training, glm = list(family = binomial))
summary(mars)
```

```{r}
library(mgcv)
colnames(training) <- make.names(colnames(training))

gam <- mgcv::gam(churn ~ s(account.length) + s(total.day.charge) + 
                   s(total.intl.calls) + s(customer.service.calls, k = 5) +
                   international.plan + voice.mail.plan, 
                 data = training,
                 family = binomial(link = "logit"), 
                 method = "REML")
summary(gam)
```

```{r}
gam2 <- mgcv::gam(churn ~ s(total.day.charge) + s(total.intl.calls) + 
                    s(customer.service.calls, k = 5) + international.plan + 
                    voice.mail.plan, data = training, 
                  family = binomial(link = "logit"), method = "REML")
summary(gam2)
```

```{r}
library(xgboost)
set.seed(3920)

train_x <- model.matrix(churn ~ ., data = training)[, -1]
train_y <- training$churn

xgb <- xgb.cv(
  objective = "binary:logistic",
  eval_metric = "auc",
  subsample = 0.5,
  data = train_x,
  label = train_y,
  nrounds = 50,
  nfold = 10
)

xgb_results <- as.data.frame(xgb$evaluation_log)
xgb_results %>% arrange(desc(test_auc_mean))
```

```{r}
library(caret)
set.seed(3920)

train_y <- as.factor(train_y)

tune_grid <- expand.grid(
  nrounds = 10,
  eta = c(0.1, 0.2, 0.3),
  max_depth = c(1:5),
  gamma = 0,
  colsample_bytree = 1,
  min_child_weight = 1,
  subsample = c(0.5, 1)
)

xgb.caret <- train(x = train_x, y = train_y,
      method = "xgbTree",
      tuneGrid = tune_grid,
      trControl = trainControl(method = 'cv', number = 10))

plot(xgb.caret)
```

```{r}
xgb1 <- xgboost(
  objective = "binary:logistic",
  eval_metric = "auc",
  subsample = 1,
  data = train_x,
  label = as.numeric(train_y) - 1,
  nrounds = 10,
  eta = 0.3,
  max_depth = 3
)

xgb.importance(feature_names = colnames(train_x), model = xgb1)
```
