---
title: "ML HW II"
author: "Andrew Lewis"
date: "2024-11-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Loading in given data
library(readr)
insurance_t <- read_csv("insurance_t.csv")
```

```{r}
# Creating missing columns for all variables with missing values
library(dplyr)
insurance_t <- insurance_t %>% mutate(AGE_M = ifelse(is.na(AGE), 1, 0)) %>% 
  mutate(INCOME_M = ifelse(is.na(INCOME), 1, 0)) %>% 
  mutate(LORES_M = ifelse(is.na(LORES), 1, 0)) %>% 
  mutate(HMVAL_M = ifelse(is.na(HMVAL), 1, 0)) %>%
  mutate(PHONE_M = ifelse(is.na(PHONE), 1, 0)) %>%
  mutate(POS_M = ifelse(is.na(POS), 1, 0)) %>%
  mutate(POSAMT_M = ifelse(is.na(POSAMT), 1, 0)) %>%
  mutate(INV_M = ifelse(is.na(INV), 1, 0)) %>%
  mutate(INVBAL_M = ifelse(is.na(INVBAL), 1, 0)) %>%
  mutate(CC_M = ifelse(is.na(CC), 1, 0)) %>%
  mutate(CCBAL_M = ifelse(is.na(CCBAL), 1, 0)) %>%
  mutate(CCPURC_M = ifelse(is.na(CCPURC), 1, 0)) %>%
  mutate(ACCTAGE_M = ifelse(is.na(ACCTAGE), 1, 0)) %>%
  mutate(CRSCORE_M = ifelse(is.na(CRSCORE), 1, 0))
```

```{r}
# Imputing continuous variables
insurance_t$AGE[is.na(insurance_t$AGE)] <- median(insurance_t$AGE, na.rm = TRUE)
insurance_t$INCOME[is.na(insurance_t$INCOME)] <- median(insurance_t$INCOME, na.rm = TRUE)
insurance_t$LORES[is.na(insurance_t$LORES)] <- median(insurance_t$LORES, na.rm = TRUE)
insurance_t$HMVAL[is.na(insurance_t$HMVAL)] <- median(insurance_t$HMVAL, na.rm = TRUE)
insurance_t$PHONE[is.na(insurance_t$PHONE)] <- median(insurance_t$PHONE, na.rm = TRUE)
insurance_t$POS[is.na(insurance_t$POS)] <- median(insurance_t$POS, na.rm = TRUE)
insurance_t$POSAMT[is.na(insurance_t$POSAMT)] <- median(insurance_t$POSAMT, na.rm = TRUE)
insurance_t$INVBAL[is.na(insurance_t$INVBAL)] <- median(insurance_t$INVBAL, na.rm = TRUE)
insurance_t$CCBAL[is.na(insurance_t$CCBAL)] <- median(insurance_t$CCBAL, na.rm = TRUE)
insurance_t$ACCTAGE[is.na(insurance_t$ACCTAGE)] <- median(insurance_t$ACCTAGE, na.rm = TRUE)
insurance_t$CRSCORE[is.na(insurance_t$CRSCORE)] <- median(insurance_t$CRSCORE, na.rm = TRUE)
```

```{r}
# Imputing categorical variables
library(DescTools)
insurance_t$INV[is.na(insurance_t$INV)] <- Mode(na.omit(insurance_t$INV))
insurance_t$CC[is.na(insurance_t$CC)] <- Mode(na.omit(insurance_t$CC))
insurance_t$CCPURC[is.na(insurance_t$CCPURC)] <- Mode(na.omit(insurance_t$CCPURC))
```

```{r}
# Converting categorical variables to factors
insurance_t$INS <- as.factor(insurance_t$INS)
insurance_t$DDA <- as.factor(insurance_t$DDA)
insurance_t$DIRDEP <- as.factor(insurance_t$DIRDEP)
insurance_t$SAV <- as.factor(insurance_t$SAV)
insurance_t$ATM <- as.factor(insurance_t$ATM)
insurance_t$CD <- as.factor(insurance_t$IRA)
insurance_t$INV <- as.factor(insurance_t$INV)
insurance_t$MM <- as.factor(insurance_t$MM)
insurance_t$CC <- as.factor(insurance_t$CC)
insurance_t$SDB <- as.factor(insurance_t$SDB)
insurance_t$INAREA <- as.factor(insurance_t$INAREA)
insurance_t$BRANCH <- as.factor(insurance_t$BRANCH)
insurance_t$NSF <- as.factor(insurance_t$NSF)
insurance_t$MMCRED <- as.factor(insurance_t$MMCRED)
insurance_t$CCPURC <- as.factor(insurance_t$CCPURC)
insurance_t <- insurance_t %>%
  mutate(across((ncol(insurance_t) - 13):ncol(insurance_t), as.factor))
```

```{r}
# Ensuring continuous variables match indicators
insurance_t$POSAMT[insurance_t$POS == 0] <- 0
insurance_t$INVBAL[insurance_t$INV == 0] <- 0
insurance_t$CCBAL[insurance_t$CC == 0] <- 0
insurance_t$CCPURC[insurance_t$CC == 0] <- 0
```

```{r}
set.seed(12345)
library(randomForest)
tuneRF(x =  insurance_t %>% select(-INS), y = insurance_t$INS, 
       plot = TRUE, ntreeTry = 100, stepFactor = 0.5)
```

```{r}
set.seed(12345)
rf.ins <- randomForest(INS ~ ., data = insurance_t, ntree = 100, mtry = 7, importance = TRUE)
```

```{r}
plot(rf.ins, main = "Number of Trees Compared to MSE")
```

```{r}
varImpPlot(rf.ins, sort = TRUE, n.var = 10, main = "Top 10 - Variable Importance")
```

```{r}
importance(rf.ins)
```

```{r}
# Collecting RF predictions on the training set
insurance_t$p_hat <- as.numeric(predict(rf.ins, type = "response"))

# Plotting the ROC curve
library(ROCit)
rf_roc <- rocit(insurance_t$p_hat, insurance_t$INS)
plot(rf_roc)
rf_roc$AUC
```

```{r}
train_x <- model.matrix(INS ~ . - p_hat, data = insurance_t)[, -1]
train_y <- as.numeric(insurance_t$INS) - 1

library(xgboost)

set.seed(12345)
xgb.ins <- xgboost(data = train_x, label = train_y, subsample = 0.5, nrounds = 50, objective = "binary:logistic")
```

```{r}
library(caret)
train_y <- as.factor(insurance_t$INS)

set.seed(12345)
xgb.ins.caret <- train(x = train_x, y = train_y,
      method = "xgbTree",
      tuneGrid = tune_grid,
      trControl = trainControl(method = 'cv', number = 10, classProbs = T),
      metric = "ROC")

plot(xgb.ins.caret)
```

```{r}
xgbcv.ins <- xgb.cv(data = train_x, label = train_y, subsample = 0.5, nrounds = 50, objective = "binary:logistic", nfold = 10)
```

```{r}
xgb.importance(feature_names = colnames(train_x), model = xgb.ins)
```

```{r}
xgb.ggplot.importance(xgb.importance(feature_names = colnames(train_x), model = xgb.ins))
```

```{r}
# Collecting RF predictions on the training set
insurance_t$p_hat2 <- predict(xgb.ins, newdata = train_x)

# Plotting the ROC curve
library(ROCit)
xgb_roc <- rocit(insurance_t$p_hat2, insurance_t$INS)
plot(xgb_roc)
xgb_roc$AUC
```













